### ISSUE TITLE
linkchecker can't find localization files

### ISSUE THREAD

**Issue by florianjacob** [linkcheck/linkchecker#102]
When I call linkchecker on the command line, it exits before doing anything with this error message on trying to access its localization files:
```
$> linkchecker
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 30, in <module>
    import linkcheck
  File "/usr/lib/python2.7/site-packages/linkcheck/__init__.py", line 137, in <module>
    init_i18n()
  File "/usr/lib/python2.7/site-packages/linkcheck/__init__.py", line 124, in init_i18n
    i18n.init(configdata.name.lower(), locdir, loc=loc)
  File "/usr/lib/python2.7/site-packages/linkcheck/i18n.py", line 94, in init
    install_language(default_language)
  File "/usr/lib/python2.7/site-packages/linkcheck/i18n.py", line 100, in install_language
    languages=[get_lang(language)], fallback=True)
  File "/usr/lib/python2.7/site-packages/linkcheck/i18n.py", line 110, in get_translator
    languages=languages, class_=translatorklass, fallback=fallback)
  File "/usr/lib/python2.7/gettext.py", line 553, in translation
    with open(mofile, 'rb') as fp:
IOError: [Errno 21] Is a directory: u'/usr/share/locale/de/LC_MESSAGES/linkchecker.mo'
```

The problem seems to be in the directory structure created by `setup.py`:
```
/usr/share/locale/
├── fr/
│   └── LC_MESSAGES/
│       └── linkchecker.mo/
│           └── fr.mo
├── es/
│   └── LC_MESSAGES/
│       └── linkchecker.mo/
│           └── es.mo
└── de/
    └── LC_MESSAGES/
        └── linkchecker.mo/
            └── de.mo
```
I assume the lowest level of the tree is created accidentally, but I did not understand what causes this behaviour. Workaround is to start linkchecker with `LC_ALL=C`.

version: linkchecker 9.4 from [AUR](https://aur.archlinux.org/packages/linkchecker/)
python 2.7
setuptools 36.2.7-1

(Originally reported at https://github.com/wummel/linkchecker/issues/728 )

**Comment by mgedmin** [comment]
I'm not an Arch user, but AFAIU their [build procedure](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linkchecker) does

    python2 setup.py build || return 1
    python2 setup.py install --root=$pkgdir || return 1

**Comment by mgedmin** [comment]
I can reproduce:

    python setup.py build
    python setup.py install --root=/tmp/wtf

creates `/tmp/wtf/home/mg/.venv/share/locale/fr/LC_MESSAGES/linkchecker.mo/fr.mo` etc.

**Comment by mgedmin** [comment]
What linkchecker is trying to do ([rename the files during installation](https://github.com/linkcheck/linkchecker/blob/6919dc8c4c68db0b9618a435e8589f6ba962440d/setup.py#L289-L294)) is impossible:

> data_files specifies a sequence of (directory, files) pairs in the following way:

> Note that you can specify the directory names where the data files will be installed, but you cannot rename the data files themselves.

-- https://docs.python.org/2/distutils/setupscript.html#installing-additional-files

What linkchecker's setup.py should be doing is copy the `po/*.mo` files into a set of subdirectories somewhere under `build/`, and then list those in data_files.  I think.  I'm not exactly an expert on setuptools scripts.

What are other distro packages doing?  Debian: installs mo files directly, one by one (actually, it installs only de.mo and forgets all the others!).

**Comment by mgedmin** [comment]
Oops!  I accidentally pushed my proposed ~~hack~~ fix into master instead of a branch.  What now?

cc: @anarcat

**Comment by anarcat** [comment]
hehe... we talk! :)

i would suggest you push a revert of that patch (`git revert d94bd0e`) first off...

i was about to suggest you look at how my other project (monkeysign) does it, but then it turns out that "pip install" doesn't ship the translation files either! for what it's worth, monkeysign has a [function to build the .mo files](https://0xacab.org/monkeysphere/monkeysign/blob/2.x/monkeysign/translation.py#L42) but [nothing special in the setup.py to deploy those](https://0xacab.org/monkeysphere/monkeysign/blob/2.x/setup.py).

obviously, the debian package of monkeysign doesn't have that issue, but oddly enough I can't figure out *why*. FWIW, the .mo files get installed in `/usr/lib/python2.7/dist-packages/monkeysign/po` there, which corresponds to the [package_data](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) field in setup.py. that path is then found from the `pkg_resources` module, [here](https://0xacab.org/monkeysphere/monkeysign/blob/2.x/monkeysign/translation.py#L28). that code was stolen from the [deluge](http://deluge-torrent.org/) source code so we may want to look there for inspiration as well.

so I'm not sure your solution is such a "hack". installing non-python files isn't exactly a well-established practice in Python installers, and translation is often a neglected part of *any* software, so I'm not surprised there are not well established standards here.

**Comment by anarcat** [comment]
why is't it simply:

```diff
 def list_message_files (package, suffix=".mo"):
     """Return list of all found message files and their installation paths."""
     for fname in glob.glob("po/*" + suffix):
         # basename (without extension) is a locale name
         localename = os.path.splitext(os.path.basename(fname))[0]
         domainname = "%s.mo" % package.lower()
-        yield (fname, os.path.join(
"share", "locale", localename, "LC_MESSAGES", domainname))
+        yield (fname, os.path.join(
"share", "locale", localename, "LC_MESSAGES"))
```

**Comment by mgedmin** [comment]
> why isn't it simply

Because we need the file to be named `linkchecker.mo`, and not `fr.mo`.  (The directory is `/usr/share/locale/fr/LC_MESSAGES`, and it's shared between all the programs on the system.)

I'll revert and create a proper PR.

**Comment by mgedmin** [comment]
BTW @anarcat what do you think about restricting direct pushes to git master, including for administrators, to prevent further accidents like this?

Downside: it would make releases using helper tools like [zest.releaser](https://pypi.python.org/pypi/zest.releaser) more difficult, since those expect to be able to push version/changelog changes directly to master.  (Not that we can do releases, until the PyPI situation is resolved, but still.)

**Comment by mgedmin** [comment]
> obviously, the debian package of monkeysign doesn't have that issue, but oddly enough I can't figure out why. FWIW, the .mo files get installed in /usr/lib/python2.7/dist-packages/monkeysign/po there

Are you explicitly telling gettext where to find the .mo files?  Because by default I believe it only looks in /usr/share/locale/ (and /usr/local/share/locale).

We could be doing that too, to make `pip install linkchecker` work (eventually), since I don't think pip will let us write arbitrary files outside Python's site-packages.

(Apologies for being too lazy to look up the documentation of gettext/pip/setuptools/distutils to see what is and isn't allowed.)

**Comment by anarcat** [comment]
On 2017-11-02 17:05:58, Marius Gedminas wrote:
> BTW @anarcat what do you think about restricting direct pushes to git master, including for administrators, to prevent further accidents like this?

Do it.

**Comment by anarcat** [comment]
On 2017-11-02 17:08:25, Marius Gedminas wrote:
>> obviously, the debian package of monkeysign doesn't have that issue, but oddly enough I can't figure out why. FWIW, the .mo files get installed in /usr/lib/python2.7/dist-packages/monkeysign/po there
>
> Are you explicitly telling gettext where to find the .mo files?  Because by default I believe it only looks in /usr/share/locale/ (and /usr/local/share/locale).

I am, yes.

**Comment by mgedmin** [comment]
> Do it.

Done (checked the bottom two checkboxes at https://github.com/linkcheck/linkchecker/settings/branches/master).

**Comment by florianjacob** [comment]
I can confirm this just works now, after I reinstalled linkchecker from AUR. Thank you! 🎉
