### ISSUE TITLE
Problem with in-page anchors when anchor-checking is disabled

### ISSUE THREAD

**Issue by mstanleyjones** [linkcheck/linkchecker#54]
I am getting the following failure:

```none
URL        `#nginx'
Name       `NGINX'
Parent URL https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/use-a-load-balancer/, line 261, col 22
Base       https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/
Real URL   https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/#nginx
Check time 5.101 seconds
Result     Error: 403 Forbidden
```

If you look at the `parent URL`, you can see the source where this anchor is defined and used, starting at line 260 (output is truncated):

```html
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#nginx" data-group="nginx">NGINX</a></li>
  <li><a data-toggle="tab" href="#haproxy" data-group="haproxy">HAProxy</a></li>
  <li><a data-toggle="tab" href="#aws">AWS LB</a></li>
</ul>
<div class="tab-content">
  <div id="nginx" class="tab-pane fade in active">
    <figure class="highlight">
```

The code works fine on the page. The weird thing is that the `Real URL` is wrong here. It should be `https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/use-a-load-balancer/` but it is getting set to `https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/#nginx` (up a level, and with the anchor added to the actual URL).

So this seems to be a bug in two ways:

- It is sending the anchor as part of the URL even though anchor-checking is disabled
- It is getting the `Real URL` wrong which is causing a 403 error

Perhaps it is not correctly formulating the real URL. It should be using the base href + the directory and filename (in this case `index.html`.

It's weird that it is only breaking for this link and no other ones on this specific page.

**Comment by anarcat** [comment]
I wasn't able to confirm the exact HTML standard that confirms this, but my research seem to say that, on a given http://example.com/foo site where you have a `<base href="http://example.com/" />` tag, `<a href="#bar">bar</a>` will link to http://example.com/#bar, and not http://example.com/foo#bar as you would expect.

See [this discussion](http://stackoverflow.com/questions/8108836/make-anchor-links-refer-to-the-current-page-when-using-base) and [this post](https://rogerkeays.com/blog/using-base-href-with-anchors) for examples.

> The code works fine on the page.

Really? Where?

If I look at https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/use-a-load-balancer/ - there are absolute links there, not relative:

    <a href="/datacenter/dtr/2.2/guides/admin/configure/use-a-load-balancer/#health-check-endpoints" class="nomunge">Health check endpoints</a>

So of course that works. :) If, using a DOM inspector, I change the above link to:

    <a href="#health-check-endpoints" class="nomunge">Health check endpoints</a>

The link points at https://docs.docker.com/datacenter/dtr/2.2/guides/admin/configure/#health-check-endpoints. So if Linkchecker is wrong, so are Firefox and Chromium. This is because of this tag in your `<head>`:

    <base href="/datacenter/dtr/2.2/guides/admin/configure/">

> So this seems to be a bug in two ways:
>
> 1. It is sending the anchor as part of the URL even though anchor-checking is disabled

That could be an issue, however - how did you disable anchor-checking exactly?

> 2. It is getting the Real URL wrong which is causing a 403 error

I do not believe it is getting it wrong: it is correctly respecting the `<base>` tag.

Please provide a way to reproduce the issue more easily, if you still believe this is an issue in linkchecker.
