### ISSUE TITLE
Failure to detect the correct requests version

### ISSUE THREAD

**Issue by cyberjacob** [linkcheck/linkchecker#61]
When running requests version 2.13.0, linkchecker incorrectly assumes the version is below 2.2.0, as it only looks at the 3rd character of the version string (in https://github.com/linkcheck/linkchecker/blob/master/linkcheck/__init__.py#L36)

**Comment by anarcat** [comment]
Hmm... i'm not sure why you draw that conclusion. This is the code I see there:

```python
# PEP 396 has only version strings, bummer! PEP 386 is also not helpful.
requests_version = requests.__version__.split('.')
# Depends on the version scheme of Python requests
if int(requests_version[0]) < 2 or \
   (int(requests_version[0]) == 2 and int(requests_version[1]) < 4):
```

this checks the first and second characters of the version string, from what I can tell. 

could you clarify the error message you are getting, which version you're running, how it was installed, etc?

**Comment by cyberjacob** [comment]
I'm using a snapshot from 4a092c2, though it won't print it's version because of the issue.
The exact message is `This program requires Python requests 2.2.0 or later.`
I have requests version 2.13.0 installed (found by running `python -c "import requests; print requests.__version__"`)

**Comment by anarcat** [comment]
This is very weird - are you sure linkchecker is properly installed? If you look at the source you linked to again, the error message you should see is:

     raise SystemExit("This program requires Python requests 2.4.0 or later instead of %s." % requests.__version__)

ie. `This program requires Python requests 2.4.0 or later instead of 2.13.0`, not `This program requires Python requests 2.2.0 or later.`

It's possible linkchecker is loading the old linkcheck library - make sure you remove the old linkcheck version before you try again!

**Comment by cyberjacob** [comment]
yup, that would be it. Looks like I had some bits of an old version stuck in the system which were being loaded. After clearing those out and redoing a clean install, everything is working now.
