### ISSUE TITLE
introduce develop branch, make master latest stable

### ISSUE THREAD

**Issue by lpirl** [linkcheck/linkchecker#85]
Hi all,

first, thanks for this awesome link checker!

Maybe you can consider introducing a development branch (say, develop) where all the development of the next version is happening and making the master branch always point to the latest stable code.

This would make it easy (for scripts and humans) to always find and download the latest stable code.

Cheers,

Lukas

**Comment by anarcat** [comment]
i would spin that around, personally: i would have a "stable" branch for long term support. there is a 9.3.x branch exactly for that purpose, for example. when we put out a 9.4.x release, we create a branch for that and so on...

if you want some stable stuff, use the 9.3.x branch, in other words - but the master branch should be stable anyways.

**Comment by lpirl** [comment]
Alright, thanks for the reply, I see your point. The `z.y.x` branches for long-term support of (even) minor releases is a very good idea.

To clarify, this issue requests a branch with an unique, never changing name (e.g. `stable`, `latest`, `master` etc.), which always points to the latest stable code, so that one does not have to modify automation routines (scripts etc.) upon new releases.

Say one uses linkchecker with a configuration management tool. One would have to check regularly on the Web to see if there is a new release and if so, update the automation routines.
With a stable branch, this would not be necessary.

Anyway, do what you want with this suggestion :)

**Comment by anarcat** [comment]
do you have an actual situation where you checkout linkchecker from git using a configuration management engine?

or is that a theoretical argument?

i ask because I would argue that a configuration management software should probably not fetch the software from git, but use a built version from PyPI or package managers, both of which are either or officially supported releases that will get fixed fast enough in case of problems or derived from a stable branch.

i mean i understand the principle, and we could simply have a label like `stable` that we would move from stable release to stable release. but at this point, there isn't that much development here and it turns out the master branch is stable enough that it isn't worth the effort. i'd rather work on making sure the master branch is good than try to carry around a magic branch like that. :)

but i'd be happy to be convinced otherwise, especially if someone volunteers to maintain the thing. ;)

**Comment by lpirl** [comment]
> do you have an actual situation where you checkout linkchecker from git using a configuration management engine?
> or is that a theoretical argument?

Well, at least I wanted to use linkchecker that way. On systems where one does not have sufficient permissions to install linkchecker or pip system-wide, it is sometimes easier to just checkout the repository. In the case of linkchecker, I abandoned this approach due to the lack of a stable branch (in the sense of this issue).

I see your point that the code base is not very fast moving. Fair enough.
However, having the lastest stable code on `master` and developing the next release on, say, `develop` isn't really "magic" nor unusual.

Anyway, enough discussion about this banality, I'd say - no? :)
